### ISSUE TITLE
version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by denisgolius** [uchenic/compose-to-nomad#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/nomadgen", line 7, in <module>
    main(args)
  File "/home/dengolius/.local/lib/python3.8/site-packages/composenomadconvertor/produce_tasks.py", line 103, in main
    l = ComposeParser(filepath)
  File "/home/dengolius/.local/lib/python3.8/site-packages/composeparser/parse.py", line 13, in __init__
    self.lib = ctypes.CDLL(os.path.join(abs_path,"libparse.so"))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/dengolius/.local/lib/python3.8/site-packages/libparse.so)
```

![image](https://user-images.githubusercontent.com/5650611/118819159-be8a5a80-b8bd-11eb-9539-6eb728d908db.png)

Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux

So to use your tools I need to install Ubuntu 20.10 or run it from virtualenv... meh...

**Comment by uchenic** [comment]
try not to install binary package for composeparser, building it from source with go compiler should do the trick

**Comment by denisgolius** [comment]
> try not to install binary package for composeparser, building it from source with go compiler should do the trick

omg
imho: better do not use this converter instead to build composer every time by myself...

**Comment by uchenic** [comment]
I should make whl package for fixed versions of glibc, than it would try to compile it from source automatically,
Thank you for pointing this, I have tested it with only one version of glibc and one version of python.

**Comment by mpolinowski** [comment]
For those adventurous among you - how to check / update GLIBC version (on your own risk - but it worked for me on Debian 11):

## Check Version

 ````bash
ldd --version
ldd (Debian GLIBC 2.31-13+deb11u2) 2.31
````

## Update

```bash
echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list
apt-get update
apt-get -t sid install libc6 libc6-dev libc6-dbg
```

**Please remember to hash out sid main from your sources list. /etc/apt/sources.list after the reboot**

## Check Version

```bash
ldd --version
ldd (Debian GLIBC 2.32-4) 2.32
```

The Error was gone afterwards.
